# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    open_payments_url: "https://openpaymentsdata.cms.gov"

services:
    site_scraper:
        class:      EIdeas\OpenPayments\ScraperBundle\Scraper\SiteScraper
        arguments:  ["@guzzle", "@cookie_jar", "@scraper_adapter_factory", "@scraper_job"]

    scraper_adapter_factory:
        class:      EIdeas\OpenPayments\ScraperBundle\Scraper\Adapter\AdapterFactory
        arguments:  ["%open_payments_url%"]

    guzzle:
        class:      GuzzleHttp\Client
        arguments:  []
        
    cookie_jar:
        class:      GuzzleHttp\Cookie\CookieJar

    document_manager:
        class:      EIdeas\OpenPayments\ScraperBundle\Document\DocumentManager
        arguments:  ["@doctrine_mongodb"]

    scraper_job:
        class:      EIdeas\OpenPayments\ScraperBundle\Scraper\Job\ScraperJob
        arguments:  ["@document_manager", "@doctor_payment_processor"]

    doctor_payment_processor:
        class:      EIdeas\OpenPayments\ScraperBundle\Scraper\Job\DoctorPaymentProcessor
        arguments:  ["@document_manager"]

    monolog_line_formatter:
        class: Monolog\Formatter\LineFormatter
        calls:
            - [includeStacktraces]